Itr-1: Feat: initialize react app
MilaKolasava/react-fundamentals pull request #1
Opened 2022-07-02 18:05 UTC by MilaKolasava

Added header and jumbotron.

2022-07-03 08:00 UTC, glebpigulevsky requested changes
lets make a clean code. project requires lint.

2022-07-03 08:00 UTC, glebpigulevsky commented on src/App.tsx
> +
extra empty line

2022-07-03 08:00 UTC, glebpigulevsky commented on src/App.tsx
> +        <Jumbatron />
error in writing Jumbotron

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +
extra empty line

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +
extra empty line

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +    width: 100%;
extra spaces. could you set up lint for your project?

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +  .navigation {
empty line requires between style selectors

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +      font-size: 10px;
extra spaces

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.tsx
> +            </nav>
extra spaces( it caoud be fixed with lint)

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Jumbatron.tsx
> +    </div>
```suggestion
    <div className='main-picture' />
```

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Jumbatron.css
> +    height: 93vh;
calc(100vw - height of header)

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +    padding-top: 0.3rem;
absolute unit

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +    width: 100vw;
why do you have for one selector two width properties?

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.css
> +    margin: 0 auto;
why do you need margin 0 auto for element with width equal 100vw?

2022-07-03 08:00 UTC, glebpigulevsky commented on src/Header.tsx
> +    <div className='wrapper'>
I think this div is extra

2022-07-04 21:16 UTC, MilaKolasava commented on src/App.tsx
> +
done

2022-07-04 21:17 UTC, MilaKolasava commented on src/Header.css
> +
done

2022-07-04 21:17 UTC, MilaKolasava commented on src/Header.css
> +
done

2022-07-04 21:33 UTC, MilaKolasava commented on src/Header.css
> +    width: 100%;
I deleted extra spaces, but my lint broke my app

2022-07-04 21:33 UTC, MilaKolasava commented on src/Header.css
> +  .navigation {
done

2022-07-04 21:33 UTC, MilaKolasava commented on src/Header.css
> +      font-size: 10px;
done

2022-07-04 21:34 UTC, MilaKolasava commented on src/Header.tsx
> +            </nav>
done

2022-07-04 21:40 UTC, MilaKolasava commented on src/App.tsx
> +        <Jumbatron />
done

2022-07-05 17:05 UTC, MilaKolasava commented on src/Jumbatron.tsx
> +    </div>
done

2022-07-05 17:09 UTC, MilaKolasava commented on src/Header.tsx
> +    <div className='wrapper'>
Yes, you are right. I delete extra div.

2022-07-05 17:40 UTC, MilaKolasava commented on src/Jumbatron.css
> +    height: 93vh;
done, but I corrected height calc(100vh - ..)

2022-07-05 17:42 UTC, MilaKolasava commented on src/Header.css
> +    width: 100vw;
i fogot delet one of them, now I done

2022-07-05 17:44 UTC, MilaKolasava commented on src/Header.css
> +    margin: 0 auto;
deleted margin: 0 auto - it was redundant.

2022-07-05 19:13 UTC, glebpigulevsky approved these changes
good job!

2022-07-05 19:15 UTC, merged