itr-5: feat: add modal window
MilaKolasava/react-fundamentals pull request #3
Opened 2022-07-09 16:02 UTC by MilaKolasava

2022-07-10 06:17 UTC, glebpigulevsky requested changes
two minor comments

2022-07-10 06:17 UTC, glebpigulevsky commented on src/components/ModalWindow/ModalWindow.css
> +.modalContent {
empty line between style selectors

2022-07-10 06:17 UTC, glebpigulevsky commented on src/components/ModalWindow/ModalWindow.tsx
> +      <div className="modalContent"></div>
you can use selfclosing of empty div

2022-07-11 11:33 UTC, MilaKolasava commented on src/components/ModalWindow/ModalWindow.css
> +.modalContent {
done

2022-07-11 11:33 UTC, glebpigulevsky approved these changes
good job!

2022-07-11 11:33 UTC, MilaKolasava commented on src/components/ModalWindow/ModalWindow.tsx
> +      <div className="modalContent"></div>
done

2022-07-11 14:31 UTC, merged